// 技能节点数据结构
export interface SkillNode {
  id: string;
  name: string;
  description: string;
  category: "language" | "framework" | "tool" | "concept";
  difficulty: "beginner" | "intermediate" | "advanced";
  estimatedHours: number;
  prerequisites: string[];
  resources: {
    docs?: string;
    tutorials?: string[];
  };
  icon: string;
  gradient: string;
}

// 技能树数据
export const skillsData: SkillNode[] = [
  // 第一层：基础
  {
    id: "web-basics",
    name: "Web基础",
    description: "Web开发的基础知识",
    category: "concept",
    difficulty: "beginner",
    estimatedHours: 0,
    prerequisites: [],
    resources: {},
    icon: "🌐",
    gradient: "from-gray-500 to-gray-600",
  },

  // 第二层：核心语言
  {
    id: "html",
    name: "HTML",
    description: "网页结构标记语言",
    category: "language",
    difficulty: "beginner",
    estimatedHours: 20,
    prerequisites: ["web-basics"],
    resources: {
      docs: "https://developer.mozilla.org/zh-CN/docs/Web/HTML",
    },
    icon: "📄",
    gradient: "from-red-500 to-orange-500",
  },
  {
    id: "css",
    name: "CSS",
    description: "网页样式设计",
    category: "language",
    difficulty: "beginner",
    estimatedHours: 30,
    prerequisites: ["html"],
    resources: {
      docs: "https://developer.mozilla.org/zh-CN/docs/Web/CSS",
    },
    icon: "🎨",
    gradient: "from-blue-500 to-cyan-500",
  },
  {
    id: "javascript",
    name: "JavaScript",
    description: "网页动态交互",
    category: "language",
    difficulty: "intermediate",
    estimatedHours: 80,
    prerequisites: ["html", "css"],
    resources: {
      docs: "https://developer.mozilla.org/zh-CN/docs/Web/JavaScript",
    },
    icon: "⚡",
    gradient: "from-yellow-500 to-amber-500",
  },

  // 第三层：前端进阶工具
  {
    id: "sass",
    name: "Sass",
    description: "CSS预处理器",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 10,
    prerequisites: ["css"],
    resources: {
      docs: "https://sass-lang.com/",
    },
    icon: "💅",
    gradient: "from-pink-500 to-rose-500",
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    description: "原子化CSS框架",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 15,
    prerequisites: ["css"],
    resources: {
      docs: "https://tailwindcss.com/",
    },
    icon: "🌊",
    gradient: "from-cyan-400 to-blue-500",
  },
  {
    id: "typescript",
    name: "TypeScript",
    description: "类型安全的JavaScript",
    category: "language",
    difficulty: "intermediate",
    estimatedHours: 40,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://www.typescriptlang.org/",
    },
    icon: "🔷",
    gradient: "from-blue-400 to-blue-600",
  },

  // 第四层：前端框架
  {
    id: "react",
    name: "React",
    description: "组件化UI库",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 60,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://react.dev/",
    },
    icon: "⚛️",
    gradient: "from-cyan-500 to-blue-500",
  },
  {
    id: "vue",
    name: "Vue",
    description: "渐进式框架",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 50,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://vuejs.org/",
    },
    icon: "💚",
    gradient: "from-green-500 to-emerald-500",
  },

  // 第五层：React 生态
  {
    id: "redux",
    name: "Redux",
    description: "状态管理库",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["react"],
    resources: {
      docs: "https://redux.js.org/",
    },
    icon: "🔄",
    gradient: "from-purple-500 to-indigo-500",
  },
  {
    id: "react-router",
    name: "React Router",
    description: "React路由管理",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 10,
    prerequisites: ["react"],
    resources: {
      docs: "https://reactrouter.com/",
    },
    icon: "🧭",
    gradient: "from-blue-400 to-cyan-400",
  },
  {
    id: "nextjs",
    name: "Next.js",
    description: "React全栈框架",
    category: "framework",
    difficulty: "advanced",
    estimatedHours: 40,
    prerequisites: ["react"],
    resources: {
      docs: "https://nextjs.org/",
    },
    icon: "▲",
    gradient: "from-gray-800 to-gray-600",
  },

  // Vue 生态
  {
    id: "vue-router",
    name: "Vue Router",
    description: "Vue路由管理",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 10,
    prerequisites: ["vue"],
    resources: {
      docs: "https://router.vuejs.org/",
    },
    icon: "🗺️",
    gradient: "from-green-400 to-emerald-400",
  },
  {
    id: "pinia",
    name: "Pinia",
    description: "Vue状态管理",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 15,
    prerequisites: ["vue"],
    resources: {
      docs: "https://pinia.vuejs.org/",
    },
    icon: "🍍",
    gradient: "from-yellow-500 to-green-500",
  },
  {
    id: "nuxt",
    name: "Nuxt",
    description: "Vue全栈框架",
    category: "framework",
    difficulty: "advanced",
    estimatedHours: 35,
    prerequisites: ["vue"],
    resources: {
      docs: "https://nuxt.com/",
    },
    icon: "💚",
    gradient: "from-green-600 to-teal-600",
  },

  // 构建工具
  {
    id: "webpack",
    name: "Webpack",
    description: "模块打包工具",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://webpack.js.org/",
    },
    icon: "📦",
    gradient: "from-blue-600 to-cyan-600",
  },
  {
    id: "vite",
    name: "Vite",
    description: "快速构建工具",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 10,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://vitejs.dev/",
    },
    icon: "⚡",
    gradient: "from-purple-600 to-blue-600",
  },

  // 后端分支
  {
    id: "nodejs",
    name: "Node.js",
    description: "JavaScript服务器运行时",
    category: "language",
    difficulty: "intermediate",
    estimatedHours: 50,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://nodejs.org/",
    },
    icon: "🟢",
    gradient: "from-green-600 to-emerald-600",
  },
  {
    id: "express",
    name: "Express",
    description: "Node.js Web框架",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["nodejs"],
    resources: {
      docs: "https://expressjs.com/",
    },
    icon: "🚂",
    gradient: "from-gray-700 to-gray-900",
  },
  {
    id: "nestjs",
    name: "NestJS",
    description: "企业级Node框架",
    category: "framework",
    difficulty: "advanced",
    estimatedHours: 45,
    prerequisites: ["nodejs", "typescript"],
    resources: {
      docs: "https://nestjs.com/",
    },
    icon: "🐱",
    gradient: "from-red-500 to-pink-500",
  },

  // Python 后端
  {
    id: "python",
    name: "Python",
    description: "通用编程语言",
    category: "language",
    difficulty: "beginner",
    estimatedHours: 60,
    prerequisites: ["web-basics"],
    resources: {
      docs: "https://docs.python.org/",
    },
    icon: "🐍",
    gradient: "from-blue-600 to-yellow-500",
  },
  {
    id: "flask",
    name: "Flask",
    description: "轻量级Python框架",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["python"],
    resources: {
      docs: "https://flask.palletsprojects.com/",
    },
    icon: "🧪",
    gradient: "from-gray-600 to-slate-700",
  },
  {
    id: "django",
    name: "Django",
    description: "全功能Python框架",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 50,
    prerequisites: ["python"],
    resources: {
      docs: "https://www.djangoproject.com/",
    },
    icon: "🎸",
    gradient: "from-green-700 to-emerald-800",
  },
  {
    id: "fastapi",
    name: "FastAPI",
    description: "现代Python API框架",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 35,
    prerequisites: ["python"],
    resources: {
      docs: "https://fastapi.tiangolo.com/",
    },
    icon: "⚡",
    gradient: "from-teal-600 to-cyan-600",
  },

  // 数据库
  {
    id: "sql-basics",
    name: "SQL基础",
    description: "关系型数据库语言",
    category: "language",
    difficulty: "beginner",
    estimatedHours: 30,
    prerequisites: ["web-basics"],
    resources: {},
    icon: "📊",
    gradient: "from-indigo-500 to-purple-500",
  },
  {
    id: "mysql",
    name: "MySQL",
    description: "开源关系型数据库",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["sql-basics"],
    resources: {
      docs: "https://dev.mysql.com/doc/",
    },
    icon: "🐬",
    gradient: "from-blue-600 to-cyan-600",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    description: "强大的开源数据库",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["sql-basics"],
    resources: {
      docs: "https://www.postgresql.org/docs/",
    },
    icon: "🐘",
    gradient: "from-blue-700 to-indigo-700",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    description: "文档型NoSQL数据库",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["nodejs"],
    resources: {
      docs: "https://www.mongodb.com/docs/",
    },
    icon: "🍃",
    gradient: "from-green-600 to-teal-600",
  },
  {
    id: "redis",
    name: "Redis",
    description: "内存数据库和缓存",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["nodejs"],
    resources: {
      docs: "https://redis.io/docs/",
    },
    icon: "🔴",
    gradient: "from-red-600 to-rose-600",
  },

  // 工具链
  {
    id: "git",
    name: "Git",
    description: "版本控制系统",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 15,
    prerequisites: ["web-basics"],
    resources: {
      docs: "https://git-scm.com/doc",
    },
    icon: "🔀",
    gradient: "from-orange-600 to-red-600",
  },
  {
    id: "github",
    name: "GitHub",
    description: "代码托管平台",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 10,
    prerequisites: ["git"],
    resources: {
      docs: "https://docs.github.com/",
    },
    icon: "🐙",
    gradient: "from-gray-800 to-gray-600",
  },
  {
    id: "docker",
    name: "Docker",
    description: "容器化平台",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["git"],
    resources: {
      docs: "https://docs.docker.com/",
    },
    icon: "🐳",
    gradient: "from-blue-500 to-cyan-500",
  },
  {
    id: "cicd",
    name: "CI/CD",
    description: "持续集成/部署",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["github", "docker"],
    resources: {},
    icon: "🔄",
    gradient: "from-green-600 to-teal-600",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    description: "容器编排系统",
    category: "tool",
    difficulty: "advanced",
    estimatedHours: 50,
    prerequisites: ["docker"],
    resources: {
      docs: "https://kubernetes.io/docs/",
    },
    icon: "☸️",
    gradient: "from-blue-600 to-indigo-600",
  },

  // 测试
  {
    id: "jest",
    name: "Jest",
    description: "JavaScript测试框架",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://jestjs.io/",
    },
    icon: "🃏",
    gradient: "from-red-600 to-pink-600",
  },

  // AI 技术
  {
    id: "prompt-engineering",
    name: "Prompt Engineering",
    description: "AI提示词工程",
    category: "concept",
    difficulty: "beginner",
    estimatedHours: 20,
    prerequisites: ["web-basics"],
    resources: {},
    icon: "✍️",
    gradient: "from-purple-500 to-pink-500",
  },
  {
    id: "llm-api",
    name: "LLM API",
    description: "大语言模型API调用",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["javascript", "prompt-engineering"],
    resources: {},
    icon: "🤖",
    gradient: "from-purple-600 to-blue-600",
  },
  {
    id: "langchain",
    name: "LangChain",
    description: "LLM应用开发框架",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 35,
    prerequisites: ["llm-api"],
    resources: {
      docs: "https://js.langchain.com/",
    },
    icon: "🔗",
    gradient: "from-green-600 to-emerald-600",
  },
  {
    id: "vector-db",
    name: "向量数据库",
    description: "AI嵌入向量存储",
    category: "tool",
    difficulty: "advanced",
    estimatedHours: 30,
    prerequisites: ["llm-api"],
    resources: {},
    icon: "🗄️",
    gradient: "from-indigo-600 to-purple-600",
  },
  {
    id: "rag",
    name: "RAG",
    description: "检索增强生成",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 40,
    prerequisites: ["langchain", "vector-db"],
    resources: {},
    icon: "📚",
    gradient: "from-orange-600 to-red-600",
  },
  // AI 进阶技术
  {
    id: "ai-agent",
    name: "AI Agent",
    description: "智能代理系统开发",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 45,
    prerequisites: ["langchain", "rag"],
    resources: {},
    icon: "🎯",
    gradient: "from-cyan-600 to-blue-600",
  },
  {
    id: "function-calling",
    name: "Function Calling",
    description: "LLM函数调用",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["llm-api"],
    resources: {},
    icon: "⚙️",
    gradient: "from-yellow-600 to-orange-600",
  },
  {
    id: "embedding",
    name: "Embedding",
    description: "文本向量化技术",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["llm-api"],
    resources: {},
    icon: "🧬",
    gradient: "from-teal-600 to-cyan-600",
  },
  {
    id: "fine-tuning",
    name: "Fine-tuning",
    description: "模型微调",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 50,
    prerequisites: ["llm-api", "python"],
    resources: {},
    icon: "🎨",
    gradient: "from-pink-600 to-rose-600",
  },
  {
    id: "multimodal-ai",
    name: "多模态AI",
    description: "图像、语音、文本融合",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 40,
    prerequisites: ["llm-api"],
    resources: {},
    icon: "🎭",
    gradient: "from-violet-600 to-purple-600",
  },
  {
    id: "ai-workflow",
    name: "AI Workflow",
    description: "AI工作流编排",
    category: "framework",
    difficulty: "advanced",
    estimatedHours: 35,
    prerequisites: ["ai-agent", "function-calling"],
    resources: {},
    icon: "🔄",
    gradient: "from-blue-700 to-indigo-700",
  },
  {
    id: "prompt-optimization",
    name: "提示词优化",
    description: "高级提示词工程",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["prompt-engineering", "llm-api"],
    resources: {},
    icon: "💎",
    gradient: "from-amber-600 to-yellow-600",
  },
  {
    id: "ai-security",
    name: "AI安全",
    description: "提示注入防御与安全",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 35,
    prerequisites: ["llm-api", "prompt-optimization"],
    resources: {},
    icon: "🛡️",
    gradient: "from-red-700 to-orange-700",
  },
  {
    id: "streaming-response",
    name: "流式响应",
    description: "实时AI响应处理",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["llm-api", "nodejs"],
    resources: {},
    icon: "⚡",
    gradient: "from-lime-600 to-green-600",
  },
  {
    id: "ai-observability",
    name: "AI可观测性",
    description: "监控和调试AI应用",
    category: "tool",
    difficulty: "advanced",
    estimatedHours: 30,
    prerequisites: ["ai-agent", "ai-workflow"],
    resources: {},
    icon: "📊",
    gradient: "from-sky-600 to-blue-600",
  },
];

// 学习路径预设
export const learningPaths = [
  {
    id: "frontend",
    name: "前端开发工程师",
    description: "成为专业的前端开发者",
    skills: [
      "web-basics",
      "html",
      "css",
      "javascript",
      "react",
      "redux",
      "react-router",
      "nextjs",
      "tailwind",
      "typescript",
    ],
    icon: "💻",
    color: "from-blue-500 to-purple-500",
  },
  {
    id: "fullstack",
    name: "全栈开发工程师",
    description: "前后端通吃的全能开发者",
    skills: [
      "web-basics",
      "html",
      "css",
      "javascript",
      "typescript",
      "react",
      "nextjs",
      "nodejs",
      "express",
      "mongodb",
      "postgresql",
      "docker",
      "git",
      "github",
    ],
    icon: "🚀",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "vue-developer",
    name: "Vue开发工程师",
    description: "Vue生态专家",
    skills: [
      "web-basics",
      "html",
      "css",
      "javascript",
      "vue",
      "vue-router",
      "pinia",
      "nuxt",
      "tailwind",
    ],
    icon: "💚",
    color: "from-green-500 to-teal-500",
  },
  {
    id: "backend",
    name: "后端开发工程师",
    description: "专注服务端开发",
    skills: [
      "web-basics",
      "javascript",
      "nodejs",
      "express",
      "nestjs",
      "sql-basics",
      "postgresql",
      "mongodb",
      "redis",
      "docker",
      "git",
    ],
    icon: "⚙️",
    color: "from-indigo-500 to-blue-500",
  },
  {
    id: "python-backend",
    name: "Python后端工程师",
    description: "Python Web开发专家",
    skills: [
      "web-basics",
      "python",
      "flask",
      "django",
      "fastapi",
      "sql-basics",
      "postgresql",
      "redis",
      "docker",
      "git",
    ],
    icon: "🐍",
    color: "from-yellow-600 to-blue-600",
  },
  {
    id: "devops",
    name: "DevOps工程师",
    description: "部署和运维专家",
    skills: [
      "web-basics",
      "git",
      "github",
      "docker",
      "cicd",
      "kubernetes",
    ],
    icon: "🔧",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "ai-developer",
    name: "AI应用开发者",
    description: "构建AI驱动的应用",
    skills: [
      "web-basics",
      "javascript",
      "typescript",
      "nodejs",
      "react",
      "nextjs",
      "prompt-engineering",
      "llm-api",
      "embedding",
      "function-calling",
      "prompt-optimization",
      "streaming-response",
      "langchain",
      "vector-db",
      "rag",
      "ai-agent",
      "ai-workflow",
      "ai-security",
      "ai-observability",
      "multimodal-ai",
    ],
    icon: "🤖",
    color: "from-purple-600 to-pink-600",
  },
];

// 难度配置
export const difficultyConfig = {
  beginner: {
    label: "入门",
    color: "bg-green-100 text-green-700 dark:bg-green-900/50 dark:text-green-300",
  },
  intermediate: {
    label: "中级",
    color: "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/50 dark:text-yellow-300",
  },
  advanced: {
    label: "高级",
    color: "bg-red-100 text-red-700 dark:bg-red-900/50 dark:text-red-300",
  },
};

// 状态配置
export const statusConfig = {
  locked: {
    label: "未解锁",
    icon: "🔒",
    color: "bg-gray-200 dark:bg-gray-700",
  },
  available: {
    label: "可学习",
    icon: "📚",
    color: "bg-blue-100 dark:bg-blue-900/30",
  },
  learning: {
    label: "学习中",
    icon: "📖",
    color: "bg-yellow-100 dark:bg-yellow-900/30",
  },
  completed: {
    label: "已完成",
    icon: "✅",
    color: "bg-green-100 dark:bg-green-900/30",
  },
  mastered: {
    label: "已精通",
    icon: "⭐",
    color: "bg-purple-100 dark:bg-purple-900/30",
  },
};
