// 技能节点数据结构
export interface SkillNode {
  id: string;
  name: string;
  description: string;
  category: "language" | "framework" | "tool" | "concept";
  difficulty: "beginner" | "intermediate" | "advanced";
  estimatedHours: number;
  prerequisites: string[];
  resources: {
    docs?: string;
    tutorials?: string[];
  };
  icon: string;
  gradient: string;
  parentId?: string; // 父技能ID（用于子技能）
  isExpandable?: boolean; // 是否可展开（有子技能）
}

// 技能树数据
export const skillsData: SkillNode[] = [
  // 第一层：基础
  {
    id: "web-basics",
    name: "Web基础",
    description: "Web开发的基础知识",
    category: "concept",
    difficulty: "beginner",
    estimatedHours: 0,
    prerequisites: [],
    resources: {},
    icon: "🌐",
    gradient: "from-gray-500 to-gray-600",
  },

  // 第二层：核心语言
  {
    id: "html",
    name: "HTML",
    description: "网页结构标记语言",
    category: "language",
    difficulty: "beginner",
    estimatedHours: 20,
    prerequisites: ["web-basics"],
    resources: {
      docs: "https://developer.mozilla.org/zh-CN/docs/Web/HTML",
    },
    icon: "📄",
    gradient: "from-red-500 to-orange-500",
  },
  {
    id: "css",
    name: "CSS",
    description: "网页样式设计",
    category: "language",
    difficulty: "beginner",
    estimatedHours: 30,
    prerequisites: ["html"],
    resources: {
      docs: "https://developer.mozilla.org/zh-CN/docs/Web/CSS",
    },
    icon: "🎨",
    gradient: "from-blue-500 to-cyan-500",
  },
  {
    id: "javascript",
    name: "JavaScript",
    description: "网页动态交互",
    category: "language",
    difficulty: "intermediate",
    estimatedHours: 80,
    prerequisites: ["html", "css"],
    resources: {
      docs: "https://developer.mozilla.org/zh-CN/docs/Web/JavaScript",
    },
    icon: "⚡",
    gradient: "from-yellow-500 to-amber-500",
  },

  // 第三层：前端进阶工具
  {
    id: "sass",
    name: "Sass",
    description: "CSS预处理器",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 10,
    prerequisites: ["css"],
    resources: {
      docs: "https://sass-lang.com/",
    },
    icon: "💅",
    gradient: "from-pink-500 to-rose-500",
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    description: "原子化CSS框架",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 15,
    prerequisites: ["css"],
    resources: {
      docs: "https://tailwindcss.com/",
    },
    icon: "🌊",
    gradient: "from-cyan-400 to-blue-500",
  },
  {
    id: "typescript",
    name: "TypeScript",
    description: "类型安全的JavaScript",
    category: "language",
    difficulty: "intermediate",
    estimatedHours: 40,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://www.typescriptlang.org/",
    },
    icon: "🔷",
    gradient: "from-blue-400 to-blue-600",
  },

  // 第四层：前端框架
  {
    id: "react",
    name: "React",
    description: "组件化UI库",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 60,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://react.dev/",
    },
    icon: "⚛️",
    gradient: "from-cyan-500 to-blue-500",
    isExpandable: true, // 标记为可展开
  },
  // React 子技能
  {
    id: "react-components",
    name: "组件基础",
    description: "JSX、Props、State基础",
    category: "concept",
    difficulty: "beginner",
    estimatedHours: 15,
    prerequisites: ["react"],
    resources: {},
    icon: "🧱",
    gradient: "from-cyan-400 to-blue-400",
    parentId: "react",
  },
  {
    id: "react-lifecycle",
    name: "生命周期",
    description: "组件生命周期与副作用",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 10,
    prerequisites: ["react"],
    resources: {},
    icon: "🔄",
    gradient: "from-cyan-400 to-blue-400",
    parentId: "react",
  },
  {
    id: "react-context",
    name: "Context API",
    description: "跨组件状态共享",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 8,
    prerequisites: ["react"],
    resources: {},
    icon: "🎯",
    gradient: "from-cyan-400 to-blue-400",
    parentId: "react",
  },
  {
    id: "react-performance",
    name: "性能优化",
    description: "Memo、useMemo、useCallback",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 12,
    prerequisites: ["react"],
    resources: {},
    icon: "⚡",
    gradient: "from-cyan-400 to-blue-400",
    parentId: "react",
  },
  {
    id: "vue",
    name: "Vue",
    description: "渐进式框架",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 50,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://vuejs.org/",
    },
    icon: "💚",
    gradient: "from-green-500 to-emerald-500",
  },

  // 第五层：React 生态
  {
    id: "redux",
    name: "Redux",
    description: "状态管理库",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["react"],
    resources: {
      docs: "https://redux.js.org/",
    },
    icon: "🔄",
    gradient: "from-purple-500 to-indigo-500",
  },
  {
    id: "react-router",
    name: "React Router",
    description: "React路由管理",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 10,
    prerequisites: ["react"],
    resources: {
      docs: "https://reactrouter.com/",
    },
    icon: "🧭",
    gradient: "from-blue-400 to-cyan-400",
  },
  {
    id: "nextjs",
    name: "Next.js",
    description: "React全栈框架",
    category: "framework",
    difficulty: "advanced",
    estimatedHours: 40,
    prerequisites: ["react", "nodejs", "typescript"],
    resources: {
      docs: "https://nextjs.org/",
    },
    icon: "▲",
    gradient: "from-gray-800 to-gray-600",
  },

  // Vue 生态
  {
    id: "vue-router",
    name: "Vue Router",
    description: "Vue路由管理",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 10,
    prerequisites: ["vue"],
    resources: {
      docs: "https://router.vuejs.org/",
    },
    icon: "🗺️",
    gradient: "from-green-400 to-emerald-400",
  },
  {
    id: "pinia",
    name: "Pinia",
    description: "Vue状态管理",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 15,
    prerequisites: ["vue"],
    resources: {
      docs: "https://pinia.vuejs.org/",
    },
    icon: "🍍",
    gradient: "from-yellow-500 to-green-500",
  },
  {
    id: "nuxt",
    name: "Nuxt",
    description: "Vue全栈框架",
    category: "framework",
    difficulty: "advanced",
    estimatedHours: 35,
    prerequisites: ["vue"],
    resources: {
      docs: "https://nuxt.com/",
    },
    icon: "💚",
    gradient: "from-green-600 to-teal-600",
  },

  // 构建工具
  {
    id: "webpack",
    name: "Webpack",
    description: "模块打包工具",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://webpack.js.org/",
    },
    icon: "📦",
    gradient: "from-blue-600 to-cyan-600",
  },
  {
    id: "vite",
    name: "Vite",
    description: "快速构建工具",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 10,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://vitejs.dev/",
    },
    icon: "⚡",
    gradient: "from-purple-600 to-blue-600",
  },

  // 后端分支
  {
    id: "nodejs",
    name: "Node.js",
    description: "JavaScript服务器运行时",
    category: "language",
    difficulty: "intermediate",
    estimatedHours: 50,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://nodejs.org/",
    },
    icon: "🟢",
    gradient: "from-green-600 to-emerald-600",
    isExpandable: true,
  },
  // Node.js 子技能
  {
    id: "nodejs-modules",
    name: "模块系统",
    description: "CommonJS与ES Module",
    category: "concept",
    difficulty: "beginner",
    estimatedHours: 8,
    prerequisites: ["nodejs"],
    resources: {},
    icon: "📦",
    gradient: "from-green-500 to-emerald-500",
    parentId: "nodejs",
  },
  {
    id: "nodejs-async",
    name: "异步编程",
    description: "事件循环、Promise、Async",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 12,
    prerequisites: ["nodejs"],
    resources: {},
    icon: "⚡",
    gradient: "from-green-500 to-emerald-500",
    parentId: "nodejs",
  },
  {
    id: "nodejs-streams",
    name: "流处理",
    description: "Stream与Buffer处理",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 10,
    prerequisites: ["nodejs"],
    resources: {},
    icon: "🌊",
    gradient: "from-green-500 to-emerald-500",
    parentId: "nodejs",
  },
  {
    id: "express",
    name: "Express",
    description: "Node.js Web框架",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["nodejs"],
    resources: {
      docs: "https://expressjs.com/",
    },
    icon: "🚂",
    gradient: "from-gray-700 to-gray-900",
  },
  {
    id: "nestjs",
    name: "NestJS",
    description: "企业级Node框架",
    category: "framework",
    difficulty: "advanced",
    estimatedHours: 45,
    prerequisites: ["nodejs", "typescript"],
    resources: {
      docs: "https://nestjs.com/",
    },
    icon: "🐱",
    gradient: "from-red-500 to-pink-500",
  },

  // Python 后端
  {
    id: "python",
    name: "Python",
    description: "通用编程语言",
    category: "language",
    difficulty: "beginner",
    estimatedHours: 60,
    prerequisites: ["web-basics"],
    resources: {
      docs: "https://docs.python.org/",
    },
    icon: "🐍",
    gradient: "from-blue-600 to-yellow-500",
  },
  {
    id: "flask",
    name: "Flask",
    description: "轻量级Python框架",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["python"],
    resources: {
      docs: "https://flask.palletsprojects.com/",
    },
    icon: "🧪",
    gradient: "from-gray-600 to-slate-700",
  },
  {
    id: "django",
    name: "Django",
    description: "全功能Python框架",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 50,
    prerequisites: ["python"],
    resources: {
      docs: "https://www.djangoproject.com/",
    },
    icon: "🎸",
    gradient: "from-green-700 to-emerald-800",
  },
  {
    id: "fastapi",
    name: "FastAPI",
    description: "现代Python API框架",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 35,
    prerequisites: ["python"],
    resources: {
      docs: "https://fastapi.tiangolo.com/",
    },
    icon: "⚡",
    gradient: "from-teal-600 to-cyan-600",
  },

  // 数据库
  {
    id: "sql-basics",
    name: "SQL基础",
    description: "关系型数据库语言",
    category: "language",
    difficulty: "beginner",
    estimatedHours: 30,
    prerequisites: ["web-basics"],
    resources: {},
    icon: "📊",
    gradient: "from-indigo-500 to-purple-500",
  },
  {
    id: "mysql",
    name: "MySQL",
    description: "开源关系型数据库",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["sql-basics"],
    resources: {
      docs: "https://dev.mysql.com/doc/",
    },
    icon: "🐬",
    gradient: "from-blue-600 to-cyan-600",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    description: "强大的开源数据库",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["sql-basics"],
    resources: {
      docs: "https://www.postgresql.org/docs/",
    },
    icon: "🐘",
    gradient: "from-blue-700 to-indigo-700",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    description: "文档型NoSQL数据库",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["nodejs"],
    resources: {
      docs: "https://www.mongodb.com/docs/",
    },
    icon: "🍃",
    gradient: "from-green-600 to-teal-600",
  },
  {
    id: "redis",
    name: "Redis",
    description: "内存数据库和缓存",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["nodejs"],
    resources: {
      docs: "https://redis.io/docs/",
    },
    icon: "🔴",
    gradient: "from-red-600 to-rose-600",
  },

  // 工具链
  {
    id: "git",
    name: "Git",
    description: "版本控制系统",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 15,
    prerequisites: ["web-basics"],
    resources: {
      docs: "https://git-scm.com/doc",
    },
    icon: "🔀",
    gradient: "from-orange-600 to-red-600",
  },
  {
    id: "github",
    name: "GitHub",
    description: "代码托管平台",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 10,
    prerequisites: ["git"],
    resources: {
      docs: "https://docs.github.com/",
    },
    icon: "🐙",
    gradient: "from-gray-800 to-gray-600",
  },
  {
    id: "docker",
    name: "Docker",
    description: "容器化平台",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["git", "nodejs"],
    resources: {
      docs: "https://docs.docker.com/",
    },
    icon: "🐳",
    gradient: "from-blue-500 to-cyan-500",
    isExpandable: true,
  },
  // Docker 子技能
  {
    id: "docker-images",
    name: "镜像管理",
    description: "Dockerfile与镜像构建",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 8,
    prerequisites: ["docker"],
    resources: {},
    icon: "📦",
    gradient: "from-blue-400 to-cyan-400",
    parentId: "docker",
  },
  {
    id: "docker-containers",
    name: "容器操作",
    description: "容器创建、运行与管理",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 10,
    prerequisites: ["docker"],
    resources: {},
    icon: "🎛️",
    gradient: "from-blue-400 to-cyan-400",
    parentId: "docker",
  },
  {
    id: "docker-compose",
    name: "Docker Compose",
    description: "多容器应用编排",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 12,
    prerequisites: ["docker"],
    resources: {},
    icon: "🎼",
    gradient: "from-blue-400 to-cyan-400",
    parentId: "docker",
  },
  {
    id: "cicd",
    name: "CI/CD",
    description: "持续集成/部署",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["github", "docker", "express"],
    resources: {},
    icon: "🔄",
    gradient: "from-green-600 to-teal-600",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    description: "容器编排系统",
    category: "tool",
    difficulty: "advanced",
    estimatedHours: 50,
    prerequisites: ["docker", "microservices", "cicd"],
    resources: {
      docs: "https://kubernetes.io/docs/",
    },
    icon: "☸️",
    gradient: "from-blue-600 to-indigo-600",
  },

  // 运维相关技能
  {
    id: "linux",
    name: "Linux",
    description: "Linux系统管理",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 60,
    prerequisites: ["web-basics"],
    resources: {},
    icon: "🐧",
    gradient: "from-gray-800 to-gray-600",
  },
  {
    id: "shell-scripting",
    name: "Shell脚本",
    description: "Bash/Shell编程",
    category: "language",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["linux"],
    resources: {},
    icon: "📝",
    gradient: "from-green-700 to-teal-700",
  },
  {
    id: "nginx",
    name: "Nginx",
    description: "Web服务器与反向代理",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["linux"],
    resources: {
      docs: "https://nginx.org/en/docs/",
    },
    icon: "🌐",
    gradient: "from-green-600 to-emerald-600",
  },
  {
    id: "monitoring",
    name: "监控系统",
    description: "Prometheus、Grafana等",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["linux"],
    resources: {},
    icon: "📊",
    gradient: "from-orange-600 to-red-600",
  },
  {
    id: "logging",
    name: "日志管理",
    description: "ELK Stack日志分析",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["linux"],
    resources: {},
    icon: "📋",
    gradient: "from-yellow-600 to-orange-600",
  },
  {
    id: "ansible",
    name: "Ansible",
    description: "自动化配置管理",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["linux", "shell-scripting"],
    resources: {
      docs: "https://docs.ansible.com/",
    },
    icon: "🤖",
    gradient: "from-red-600 to-pink-600",
  },
  {
    id: "terraform",
    name: "Terraform",
    description: "基础设施即代码",
    category: "tool",
    difficulty: "advanced",
    estimatedHours: 35,
    prerequisites: ["linux", "docker"],
    resources: {
      docs: "https://www.terraform.io/docs",
    },
    icon: "🏗️",
    gradient: "from-purple-600 to-indigo-600",
  },
  {
    id: "jenkins",
    name: "Jenkins",
    description: "CI/CD自动化服务器",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["cicd"],
    resources: {
      docs: "https://www.jenkins.io/doc/",
    },
    icon: "👷",
    gradient: "from-red-600 to-orange-600",
  },
  {
    id: "cloud-platforms",
    name: "云平台",
    description: "AWS、阿里云、腾讯云",
    category: "tool",
    difficulty: "advanced",
    estimatedHours: 50,
    prerequisites: ["linux", "docker"],
    resources: {},
    icon: "☁️",
    gradient: "from-blue-500 to-cyan-500",
  },
  {
    id: "network-basics",
    name: "网络基础",
    description: "TCP/IP、HTTP/HTTPS",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 35,
    prerequisites: ["linux"],
    resources: {},
    icon: "🌐",
    gradient: "from-teal-600 to-cyan-600",
  },
  {
    id: "security-ops",
    name: "安全运维",
    description: "系统安全与防护",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 40,
    prerequisites: ["linux", "network-basics"],
    resources: {},
    icon: "🔐",
    gradient: "from-red-700 to-pink-700",
  },
  {
    id: "backup-recovery",
    name: "备份恢复",
    description: "数据备份与灾难恢复",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["linux"],
    resources: {},
    icon: "💾",
    gradient: "from-indigo-600 to-purple-600",
  },

  // 数据库专业技能
  {
    id: "db-design",
    name: "数据库设计",
    description: "数据建模与范式",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["sql-basics"],
    resources: {},
    icon: "📐",
    gradient: "from-blue-600 to-indigo-600",
  },
  {
    id: "db-optimization",
    name: "查询优化",
    description: "SQL优化与索引设计",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 35,
    prerequisites: ["mysql", "postgresql"],
    resources: {},
    icon: "⚡",
    gradient: "from-yellow-600 to-orange-600",
  },
  {
    id: "db-replication",
    name: "数据库复制",
    description: "主从复制与高可用",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 30,
    prerequisites: ["mysql", "postgresql"],
    resources: {},
    icon: "🔄",
    gradient: "from-green-600 to-teal-600",
  },
  {
    id: "db-backup",
    name: "数据库备份",
    description: "备份策略与恢复",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["mysql", "postgresql"],
    resources: {},
    icon: "💿",
    gradient: "from-purple-600 to-pink-600",
  },
  {
    id: "db-monitoring",
    name: "数据库监控",
    description: "性能监控与调优",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["mysql", "postgresql"],
    resources: {},
    icon: "📈",
    gradient: "from-orange-600 to-red-600",
  },
  {
    id: "elasticsearch",
    name: "Elasticsearch",
    description: "分布式搜索引擎",
    category: "tool",
    difficulty: "advanced",
    estimatedHours: 40,
    prerequisites: ["mongodb"],
    resources: {
      docs: "https://www.elastic.co/guide/",
    },
    icon: "🔍",
    gradient: "from-yellow-600 to-green-600",
  },
  {
    id: "data-warehouse",
    name: "数据仓库",
    description: "数据仓库设计与ETL",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 50,
    prerequisites: ["sql-basics", "db-design"],
    resources: {},
    icon: "🏛️",
    gradient: "from-indigo-700 to-purple-700",
  },
  {
    id: "big-data",
    name: "大数据技术",
    description: "Hadoop、Spark基础",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 60,
    prerequisites: ["sql-basics", "python"],
    resources: {},
    icon: "📊",
    gradient: "from-orange-700 to-red-700",
  },
  {
    id: "db-sharding",
    name: "分库分表",
    description: "数据库水平扩展",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 35,
    prerequisites: ["mysql", "postgresql", "db-optimization"],
    resources: {},
    icon: "🔀",
    gradient: "from-cyan-600 to-blue-600",
  },
  {
    id: "nosql-design",
    name: "NoSQL设计",
    description: "NoSQL数据建模",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["mongodb"],
    resources: {},
    icon: "🗂️",
    gradient: "from-green-700 to-emerald-700",
  },

  // 测试
  {
    id: "jest",
    name: "Jest",
    description: "JavaScript测试框架",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://jestjs.io/",
    },
    icon: "🃏",
    gradient: "from-red-600 to-pink-600",
  },

  // 前端工程化工具
  {
    id: "npm",
    name: "NPM/Yarn",
    description: "包管理工具",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 8,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://docs.npmjs.com/",
    },
    icon: "📦",
    gradient: "from-red-600 to-pink-600",
  },
  {
    id: "eslint",
    name: "ESLint",
    description: "代码质量检查",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 10,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://eslint.org/",
    },
    icon: "🔍",
    gradient: "from-purple-600 to-blue-600",
  },
  {
    id: "prettier",
    name: "Prettier",
    description: "代码格式化工具",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 5,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://prettier.io/",
    },
    icon: "✨",
    gradient: "from-pink-600 to-rose-600",
  },

  // CSS 进阶技能
  {
    id: "css-modules",
    name: "CSS Modules",
    description: "模块化CSS方案",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 8,
    prerequisites: ["css"],
    resources: {},
    icon: "🎨",
    gradient: "from-blue-500 to-cyan-500",
  },
  {
    id: "responsive-design",
    name: "响应式设计",
    description: "移动端适配与响应式布局",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["css"],
    resources: {},
    icon: "📱",
    gradient: "from-cyan-500 to-blue-500",
  },
  {
    id: "css-animation",
    name: "CSS动画",
    description: "CSS动画与过渡效果",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["css"],
    resources: {},
    icon: "💫",
    gradient: "from-purple-500 to-pink-500",
  },

  // JavaScript 进阶
  {
    id: "es6-plus",
    name: "ES6+",
    description: "现代JavaScript特性",
    category: "language",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["javascript"],
    resources: {},
    icon: "🚀",
    gradient: "from-yellow-600 to-orange-600",
  },
  {
    id: "async-programming",
    name: "异步编程",
    description: "Promise、Async/Await",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["javascript"],
    resources: {},
    icon: "⚡",
    gradient: "from-blue-600 to-indigo-600",
  },
  {
    id: "dom-manipulation",
    name: "DOM操作",
    description: "DOM API与事件处理",
    category: "concept",
    difficulty: "beginner",
    estimatedHours: 20,
    prerequisites: ["javascript"],
    resources: {},
    icon: "🎯",
    gradient: "from-green-600 to-teal-600",
  },

  // React 生态扩展
  {
    id: "react-hooks",
    name: "React Hooks",
    description: "现代React开发核心",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["react"],
    resources: {},
    icon: "🪝",
    gradient: "from-cyan-600 to-blue-600",
  },
  {
    id: "react-testing",
    name: "React Testing",
    description: "组件测试与集成测试",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["react", "jest"],
    resources: {},
    icon: "🧪",
    gradient: "from-green-600 to-emerald-600",
  },

  // 性能优化
  {
    id: "web-performance",
    name: "性能优化",
    description: "Web性能优化技术",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 35,
    prerequisites: ["javascript", "react", "nextjs"],
    resources: {},
    icon: "⚡",
    gradient: "from-orange-600 to-red-600",
  },
  {
    id: "lazy-loading",
    name: "懒加载",
    description: "代码分割与按需加载",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 15,
    prerequisites: ["react"],
    resources: {},
    icon: "🔄",
    gradient: "from-blue-500 to-purple-500",
  },

  // API 与数据获取
  {
    id: "fetch-api",
    name: "Fetch API",
    description: "HTTP请求与数据获取",
    category: "concept",
    difficulty: "beginner",
    estimatedHours: 15,
    prerequisites: ["javascript"],
    resources: {},
    icon: "🌐",
    gradient: "from-teal-600 to-cyan-600",
  },
  {
    id: "axios",
    name: "Axios",
    description: "HTTP客户端库",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 10,
    prerequisites: ["javascript"],
    resources: {
      docs: "https://axios-http.com/",
    },
    icon: "📡",
    gradient: "from-purple-600 to-pink-600",
  },
  {
    id: "graphql",
    name: "GraphQL",
    description: "现代API查询语言",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["javascript", "fetch-api"],
    resources: {
      docs: "https://graphql.org/",
    },
    icon: "⚛️",
    gradient: "from-pink-600 to-purple-600",
  },

  // 状态管理扩展
  {
    id: "zustand",
    name: "Zustand",
    description: "轻量级状态管理",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 12,
    prerequisites: ["react"],
    resources: {
      docs: "https://zustand-demo.pmnd.rs/",
    },
    icon: "🐻",
    gradient: "from-amber-600 to-orange-600",
  },
  {
    id: "react-query",
    name: "React Query",
    description: "服务端状态管理",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["react", "fetch-api"],
    resources: {
      docs: "https://tanstack.com/query/",
    },
    icon: "🔄",
    gradient: "from-red-600 to-pink-600",
  },

  // UI 组件库
  {
    id: "material-ui",
    name: "Material-UI",
    description: "React UI组件库",
    category: "framework",
    difficulty: "beginner",
    estimatedHours: 15,
    prerequisites: ["react"],
    resources: {
      docs: "https://mui.com/",
    },
    icon: "🎨",
    gradient: "from-blue-600 to-indigo-600",
  },
  {
    id: "ant-design",
    name: "Ant Design",
    description: "企业级UI设计语言",
    category: "framework",
    difficulty: "beginner",
    estimatedHours: 15,
    prerequisites: ["react"],
    resources: {
      docs: "https://ant.design/",
    },
    icon: "🐜",
    gradient: "from-blue-500 to-cyan-500",
  },

  // 浏览器相关
  {
    id: "browser-devtools",
    name: "浏览器调试",
    description: "DevTools使用技巧",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 12,
    prerequisites: ["javascript"],
    resources: {},
    icon: "🔧",
    gradient: "from-gray-600 to-gray-800",
  },
  {
    id: "web-storage",
    name: "浏览器存储",
    description: "LocalStorage、Cookie等",
    category: "concept",
    difficulty: "beginner",
    estimatedHours: 10,
    prerequisites: ["javascript"],
    resources: {},
    icon: "💾",
    gradient: "from-indigo-600 to-purple-600",
  },

  // 前端安全
  {
    id: "web-security",
    name: "Web安全",
    description: "XSS、CSRF防护",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["javascript"],
    resources: {},
    icon: "🔒",
    gradient: "from-red-600 to-orange-600",
  },

  // 辅助技能
  {
    id: "seo",
    name: "SEO优化",
    description: "搜索引擎优化",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["html", "javascript"],
    resources: {},
    icon: "🔍",
    gradient: "from-green-600 to-teal-600",
  },
  {
    id: "accessibility",
    name: "无障碍访问",
    description: "Web可访问性标准",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 18,
    prerequisites: ["html"],
    resources: {},
    icon: "♿",
    gradient: "from-blue-600 to-cyan-600",
  },

  // AI 技术
  {
    id: "prompt-engineering",
    name: "Prompt Engineering",
    description: "AI提示词工程",
    category: "concept",
    difficulty: "beginner",
    estimatedHours: 20,
    prerequisites: ["web-basics"],
    resources: {},
    icon: "✍️",
    gradient: "from-purple-500 to-pink-500",
  },
  {
    id: "llm-api",
    name: "LLM API",
    description: "大语言模型API调用",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["javascript", "prompt-engineering"],
    resources: {},
    icon: "🤖",
    gradient: "from-purple-600 to-blue-600",
  },
  {
    id: "langchain",
    name: "LangChain",
    description: "LLM应用开发框架",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 35,
    prerequisites: ["llm-api"],
    resources: {
      docs: "https://js.langchain.com/",
    },
    icon: "🔗",
    gradient: "from-green-600 to-emerald-600",
  },
  {
    id: "vector-db",
    name: "向量数据库",
    description: "AI嵌入向量存储",
    category: "tool",
    difficulty: "advanced",
    estimatedHours: 30,
    prerequisites: ["llm-api"],
    resources: {},
    icon: "🗄️",
    gradient: "from-indigo-600 to-purple-600",
  },
  {
    id: "rag",
    name: "RAG",
    description: "检索增强生成",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 40,
    prerequisites: ["langchain", "vector-db"],
    resources: {},
    icon: "📚",
    gradient: "from-orange-600 to-red-600",
  },
  // AI 进阶技术
  {
    id: "ai-agent",
    name: "AI Agent",
    description: "智能代理系统开发",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 45,
    prerequisites: ["langchain", "rag"],
    resources: {},
    icon: "🎯",
    gradient: "from-cyan-600 to-blue-600",
  },
  {
    id: "function-calling",
    name: "Function Calling",
    description: "LLM函数调用",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["llm-api"],
    resources: {},
    icon: "⚙️",
    gradient: "from-yellow-600 to-orange-600",
  },
  {
    id: "embedding",
    name: "Embedding",
    description: "文本向量化技术",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["llm-api"],
    resources: {},
    icon: "🧬",
    gradient: "from-teal-600 to-cyan-600",
  },
  {
    id: "fine-tuning",
    name: "Fine-tuning",
    description: "模型微调",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 50,
    prerequisites: ["llm-api", "python"],
    resources: {},
    icon: "🎨",
    gradient: "from-pink-600 to-rose-600",
  },
  {
    id: "multimodal-ai",
    name: "多模态AI",
    description: "图像、语音、文本融合",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 40,
    prerequisites: ["llm-api"],
    resources: {},
    icon: "🎭",
    gradient: "from-violet-600 to-purple-600",
  },
  {
    id: "ai-workflow",
    name: "AI Workflow",
    description: "AI工作流编排",
    category: "framework",
    difficulty: "advanced",
    estimatedHours: 35,
    prerequisites: ["ai-agent", "function-calling"],
    resources: {},
    icon: "🔄",
    gradient: "from-blue-700 to-indigo-700",
  },
  {
    id: "prompt-optimization",
    name: "提示词优化",
    description: "高级提示词工程",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 30,
    prerequisites: ["prompt-engineering", "llm-api"],
    resources: {},
    icon: "💎",
    gradient: "from-amber-600 to-yellow-600",
  },
  {
    id: "ai-security",
    name: "AI安全",
    description: "提示注入防御与安全",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 35,
    prerequisites: ["llm-api", "prompt-optimization"],
    resources: {},
    icon: "🛡️",
    gradient: "from-red-700 to-orange-700",
  },
  {
    id: "streaming-response",
    name: "流式响应",
    description: "实时AI响应处理",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["llm-api", "nodejs"],
    resources: {},
    icon: "⚡",
    gradient: "from-lime-600 to-green-600",
  },
  {
    id: "ai-observability",
    name: "AI可观测性",
    description: "监控和调试AI应用",
    category: "tool",
    difficulty: "advanced",
    estimatedHours: 30,
    prerequisites: ["ai-agent", "ai-workflow"],
    resources: {},
    icon: "📊",
    gradient: "from-sky-600 to-blue-600",
  },

  // ========== 后端语言与框架扩展 ==========
  {
    id: "go",
    name: "Go",
    description: "高性能后端编程语言",
    category: "language",
    difficulty: "intermediate",
    estimatedHours: 50,
    prerequisites: ["web-basics"],
    resources: {
      docs: "https://go.dev/doc/",
    },
    icon: "🐹",
    gradient: "from-cyan-500 to-blue-500",
  },
  {
    id: "gin",
    name: "Gin",
    description: "Go轻量级Web框架",
    category: "framework",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["go"],
    resources: {
      docs: "https://gin-gonic.com/docs/",
    },
    icon: "🍸",
    gradient: "from-teal-500 to-cyan-600",
  },
  {
    id: "java",
    name: "Java",
    description: "企业级编程语言",
    category: "language",
    difficulty: "intermediate",
    estimatedHours: 70,
    prerequisites: ["web-basics"],
    resources: {
      docs: "https://docs.oracle.com/javase/",
    },
    icon: "☕",
    gradient: "from-orange-600 to-red-600",
  },
  {
    id: "spring-boot",
    name: "Spring Boot",
    description: "Java企业级开发框架",
    category: "framework",
    difficulty: "advanced",
    estimatedHours: 60,
    prerequisites: ["java"],
    resources: {
      docs: "https://spring.io/projects/spring-boot",
    },
    icon: "🍃",
    gradient: "from-green-600 to-emerald-600",
  },

  // ========== API 设计与通信 ==========
  {
    id: "restful-api",
    name: "RESTful API",
    description: "REST API设计规范",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 20,
    prerequisites: ["nodejs"],
    resources: {},
    icon: "🔌",
    gradient: "from-blue-500 to-indigo-500",
  },
  {
    id: "api-docs",
    name: "API文档",
    description: "Swagger/OpenAPI规范",
    category: "tool",
    difficulty: "beginner",
    estimatedHours: 12,
    prerequisites: ["restful-api"],
    resources: {
      docs: "https://swagger.io/",
    },
    icon: "📑",
    gradient: "from-green-500 to-teal-500",
  },
  {
    id: "websocket",
    name: "WebSocket",
    description: "实时双向通信协议",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 18,
    prerequisites: ["nodejs"],
    resources: {},
    icon: "🔗",
    gradient: "from-purple-500 to-pink-500",
  },
  {
    id: "grpc",
    name: "gRPC",
    description: "高性能RPC通信框架",
    category: "tool",
    difficulty: "advanced",
    estimatedHours: 25,
    prerequisites: ["restful-api"],
    resources: {
      docs: "https://grpc.io/docs/",
    },
    icon: "📡",
    gradient: "from-cyan-600 to-blue-600",
  },
  {
    id: "message-queue",
    name: "消息队列",
    description: "RabbitMQ/Kafka异步处理",
    category: "tool",
    difficulty: "advanced",
    estimatedHours: 35,
    prerequisites: ["redis", "nodejs", "restful-api"],
    resources: {},
    icon: "📨",
    gradient: "from-orange-500 to-red-500",
  },

  // ========== 后端认证与安全 ==========
  {
    id: "jwt-auth",
    name: "JWT认证",
    description: "基于Token的身份认证",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 15,
    prerequisites: ["restful-api"],
    resources: {},
    icon: "🔑",
    gradient: "from-amber-500 to-orange-500",
  },
  {
    id: "oauth",
    name: "OAuth 2.0",
    description: "第三方授权登录",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 20,
    prerequisites: ["jwt-auth"],
    resources: {},
    icon: "🛂",
    gradient: "from-red-500 to-pink-500",
  },

  // ========== 后端数据访问与架构 ==========
  {
    id: "orm",
    name: "ORM框架",
    description: "Prisma/TypeORM/SQLAlchemy",
    category: "tool",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["sql-basics"],
    resources: {},
    icon: "🗃️",
    gradient: "from-indigo-500 to-purple-500",
  },
  {
    id: "caching-strategy",
    name: "缓存策略",
    description: "多级缓存与穿透/雪崩防护",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 25,
    prerequisites: ["redis", "nodejs", "restful-api"],
    resources: {},
    icon: "🚀",
    gradient: "from-rose-500 to-red-500",
  },
  {
    id: "microservices",
    name: "微服务架构",
    description: "服务拆分、注册与治理",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 45,
    prerequisites: ["docker", "restful-api", "message-queue"],
    resources: {},
    icon: "🧩",
    gradient: "from-blue-600 to-indigo-600",
  },
  {
    id: "backend-testing",
    name: "后端测试",
    description: "单元测试与接口集成测试",
    category: "concept",
    difficulty: "intermediate",
    estimatedHours: 25,
    prerequisites: ["restful-api"],
    resources: {},
    icon: "🧫",
    gradient: "from-green-600 to-emerald-600",
  },
  {
    id: "system-design",
    name: "系统设计",
    description: "高并发高可用架构设计",
    category: "concept",
    difficulty: "advanced",
    estimatedHours: 50,
    prerequisites: ["microservices", "caching-strategy", "message-queue"],
    resources: {},
    icon: "🎛️",
    gradient: "from-slate-600 to-gray-700",
  },
];

// 学习路径预设
export const learningPaths = [
  {
    id: "frontend",
    name: "前端开发工程师",
    description: "成为专业的前端开发者",
    skills: [
      "web-basics",
      "html",
      "css",
      "javascript",
      "dom-manipulation",
      "es6-plus",
      "async-programming",
      "typescript",
      "git",
      "npm",
      "responsive-design",
      "css-animation",
      "tailwind",
      "sass",
      "fetch-api",
      "axios",
      "react",
      "react-hooks",
      "react-router",
      "redux",
      "zustand",
      "react-query",
      "nextjs",
      "jest",
      "react-testing",
      "eslint",
      "prettier",
      "webpack",
      "vite",
      "lazy-loading",
      "web-performance",
      "browser-devtools",
      "web-storage",
      "web-security",
      "seo",
      "accessibility",
    ],
    icon: "💻",
    color: "from-blue-500 to-purple-500",
  },
  {
    id: "fullstack",
    name: "全栈开发工程师",
    description: "前后端通吃的全能开发者",
    skills: [
      // 第0层：起点
      "web-basics",

      // 第1层：基础标记
      "html",
      "css",

      // 第2层：核心语言
      "javascript",

      // 第3层：框架工具
      "typescript",
      "react",
      "nodejs",
      "git",
      "npm",
      "tailwind",
      "sass",
      "es6-plus",
      "async-programming",
      "dom-manipulation",
      "fetch-api",
      "axios",

      // 第4层：进阶技术
      "react-hooks",
      "react-router",
      "redux",
      "zustand",
      "react-query",
      "nextjs",
      "express",
      "nestjs",
      "sql-basics",
      "mysql",
      "postgresql",
      "mongodb",
      "redis",
      "orm",
      "restful-api",
      "api-docs",
      "jwt-auth",
      "github",
      "vite",
      "webpack",
      "eslint",
      "prettier",
      "jest",
      "react-testing",

      // 第5层：专家级
      "websocket",
      "grpc",
      "graphql",
      "message-queue",
      "caching-strategy",
      "backend-testing",
      "microservices",
      "docker",
      "cicd",
      "web-performance",
      "lazy-loading",
      "web-security",
      "seo",
      "accessibility",

      // 第6层：大师级
      "kubernetes",
      "system-design",
    ],
    icon: "🚀",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "vue-developer",
    name: "Vue开发工程师",
    description: "Vue生态专家",
    skills: [
      "web-basics",
      "html",
      "css",
      "javascript",
      "vue",
      "vue-router",
      "pinia",
      "nuxt",
      "tailwind",
    ],
    icon: "💚",
    color: "from-green-500 to-teal-500",
  },
  {
    id: "backend",
    name: "后端开发工程师",
    description: "专注服务端开发",
    skills: [
      "web-basics",
      "javascript",
      "nodejs",
      "typescript",
      "express",
      "nestjs",
      "sql-basics",
      "mysql",
      "postgresql",
      "mongodb",
      "redis",
      "orm",
      "restful-api",
      "api-docs",
      "jwt-auth",
      "oauth",
      "websocket",
      "grpc",
      "message-queue",
      "caching-strategy",
      "backend-testing",
      "microservices",
      "docker",
      "git",
      "github",
      "cicd",
    ],
    icon: "⚙️",
    color: "from-indigo-500 to-blue-500",
  },
  {
    id: "python-backend",
    name: "Python后端工程师",
    description: "Python Web开发专家",
    skills: [
      "web-basics",
      "python",
      "flask",
      "django",
      "fastapi",
      "sql-basics",
      "mysql",
      "postgresql",
      "redis",
      "orm",
      "restful-api",
      "api-docs",
      "jwt-auth",
      "oauth",
      "backend-testing",
      "caching-strategy",
      "message-queue",
      "docker",
      "git",
      "github",
      "cicd",
    ],
    icon: "🐍",
    color: "from-yellow-600 to-blue-600",
  },
  {
    id: "go-backend",
    name: "Go后端工程师",
    description: "高性能Go服务开发",
    skills: [
      "web-basics",
      "go",
      "gin",
      "sql-basics",
      "mysql",
      "postgresql",
      "mongodb",
      "redis",
      "orm",
      "restful-api",
      "api-docs",
      "jwt-auth",
      "grpc",
      "websocket",
      "message-queue",
      "caching-strategy",
      "backend-testing",
      "microservices",
      "system-design",
      "docker",
      "kubernetes",
      "git",
      "github",
      "cicd",
    ],
    icon: "🐹",
    color: "from-cyan-500 to-blue-600",
  },
  {
    id: "java-backend",
    name: "Java后端工程师",
    description: "企业级Java开发专家",
    skills: [
      "web-basics",
      "java",
      "spring-boot",
      "sql-basics",
      "mysql",
      "postgresql",
      "redis",
      "orm",
      "restful-api",
      "api-docs",
      "jwt-auth",
      "oauth",
      "grpc",
      "message-queue",
      "caching-strategy",
      "backend-testing",
      "microservices",
      "system-design",
      "docker",
      "kubernetes",
      "git",
      "github",
      "cicd",
      "monitoring",
    ],
    icon: "☕",
    color: "from-orange-600 to-red-600",
  },
  {
    id: "devops",
    name: "DevOps工程师",
    description: "部署和运维专家",
    skills: [
      "web-basics",
      "git",
      "github",
      "docker",
      "cicd",
      "kubernetes",
    ],
    icon: "🔧",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "ai-developer",
    name: "AI应用开发者",
    description: "构建AI驱动的应用",
    skills: [
      "web-basics",
      "javascript",
      "typescript",
      "nodejs",
      "react",
      "nextjs",
      "prompt-engineering",
      "llm-api",
      "embedding",
      "function-calling",
      "prompt-optimization",
      "streaming-response",
      "langchain",
      "vector-db",
      "rag",
      "ai-agent",
      "ai-workflow",
      "ai-security",
      "ai-observability",
      "multimodal-ai",
    ],
    icon: "🤖",
    color: "from-purple-600 to-pink-600",
  },
  {
    id: "devops-engineer",
    name: "运维工程师",
    description: "系统运维与基础设施管理",
    skills: [
      "web-basics",
      "linux",
      "shell-scripting",
      "network-basics",
      "git",
      "github",
      "nginx",
      "docker",
      "kubernetes",
      "cicd",
      "jenkins",
      "ansible",
      "terraform",
      "monitoring",
      "logging",
      "cloud-platforms",
      "security-ops",
      "backup-recovery",
    ],
    icon: "🛠️",
    color: "from-orange-600 to-red-600",
  },
  {
    id: "database-engineer",
    name: "数据库工程师",
    description: "数据库设计、优化与管理",
    skills: [
      "web-basics",
      "sql-basics",
      "mysql",
      "postgresql",
      "mongodb",
      "redis",
      "db-design",
      "db-optimization",
      "db-replication",
      "db-backup",
      "db-monitoring",
      "db-sharding",
      "nosql-design",
      "elasticsearch",
      "data-warehouse",
      "big-data",
      "linux",
      "shell-scripting",
    ],
    icon: "🗄️",
    color: "from-cyan-600 to-blue-600",
  },
];

// 难度配置
export const difficultyConfig = {
  beginner: {
    label: "入门",
    color: "bg-green-100 text-green-700 dark:bg-green-900/50 dark:text-green-300",
  },
  intermediate: {
    label: "中级",
    color: "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/50 dark:text-yellow-300",
  },
  advanced: {
    label: "高级",
    color: "bg-red-100 text-red-700 dark:bg-red-900/50 dark:text-red-300",
  },
};

// 状态配置
export const statusConfig = {
  locked: {
    label: "未解锁",
    icon: "🔒",
    color: "bg-gray-200 dark:bg-gray-700",
  },
  available: {
    label: "可学习",
    icon: "📚",
    color: "bg-blue-100 dark:bg-blue-900/30",
  },
  learning: {
    label: "学习中",
    icon: "📖",
    color: "bg-yellow-100 dark:bg-yellow-900/30",
  },
  completed: {
    label: "已完成",
    icon: "✅",
    color: "bg-green-100 dark:bg-green-900/30",
  },
  mastered: {
    label: "已精通",
    icon: "⭐",
    color: "bg-purple-100 dark:bg-purple-900/30",
  },
};
